### PR TITLE
added even lxd options

### PR DESCRIPTION
**Pull request by kent0**
Added even lxd option that is desired on some machines. It rounds down lxd to an even number.

### CODE REVIEW

**Comment by kent0** [comment]
merged since backwards compatible

**Comment by kent0** [comment]
merged since backwards compatible

**Comment by thilinarmtb** [comment]
Thanks for the PR @kent0 !! 

Can you please add a note about this in `README.md` if you don't mind?
That will be really helpful.

**Comment by kent0** [comment]
Of course, I can do that shortly

**Comment by thilinarmtb** [comment]
Thank you very much !!

**Pull request merged**
